const topics=[
['General health & safety','⚖️','Know your duties, risk assessment and site rules'],['Manual handling','📦','Plan the lift and protect your back'],['Reporting accidents','📝','Accident books, RIDDOR and investigations'],['PPE at work','🦺','Choose, wear and check protective equipment'],['Health & hygiene','🫁','Asbestos, noise, welfare and occupational health'],['Fire & emergency','🧯','Evacuate, respond and prevent fire spread'],['Work at height','🪜','Ladders, platforms and fall prevention'],['Work equipment','🛠️','Guards, defects, safe working loads'],['Special site hazards','⚠️','Confined spaces, excavations and young workers'],['Electrotechnical','⚡','Electrical safety and safe isolation'],['Environmental','🌿','Waste, dust, spills and sustainability']];
const lessons=[
['General health & safety',[['Your duty','Employers, employees and self-employed people all have duties to work safely under the Health and Safety at Work Act 1974.'],['Risk assessment','A risk assessment is a careful review of what could cause harm, followed by practical controls. It is more than paperwork.'],['Safety signs','A prohibition sign, such as “No access”, uses red, white and black.']]],
['Manual handling',[['Start with avoidance','First ask whether the load needs to be lifted at all. If not, eliminate the manual handling task.'],['Assess the lift','Consider the task, the load, the environment and individual capability before lifting.'],['Lift well','Get close to the load, keep your back in a safe posture and use strong leg muscles.']]],
['Reporting accidents',[['Record it','All workplace injuries should be recorded in the company accident book.'],['Reportable incidents','RIDDOR covers certain work-related injuries, diseases and dangerous occurrences. A fatality must be notified without delay.'],['Learn from it','Investigations identify underlying causes and help prevent recurrence - not just assign blame.']]],
['PPE at work',[['Last line of defence','Use PPE when hazards cannot be controlled another way; it must be suitable, maintained and used as instructed.'],['On highways','High-visibility clothing is especially important when working on or near a highway.'],['Hard hats','Provided hard hats must be CE or UKCA marked and worn according to the manufacturer’s instructions.']]],
['Health & hygiene',[['Asbestos','Breathing asbestos fibres can cause serious disease. Suspected asbestos must be managed safely - never disturb it.'],['Noise','Long-term exposure to high noise can cause irreversible hearing damage.'],['Welfare','Site welfare needs, including toilets, depend on the number of people on site.']]],
['Fire & emergency',[['Evacuate','On hearing a fire alarm, go promptly to the designated place of safety.'],['CO₂ extinguishers','The nozzle becomes extremely cold in use due to rapid gas expansion.'],['First response','If someone is not breathing, send for help immediately, then begin appropriate aid.']]],
['Work at height',[['Plan first','Falls from height are a leading cause of site fatalities. Avoid work at height where possible.'],['Ladders','The user must inspect a ladder before use. Ladders are for access and only short, safe work periods.'],['MEWPs','Attach a safety harness to the secure anchorage point inside the platform.']]],
['Work equipment',[['Safe working load','SWL means Safe Working Load: lifting equipment must be marked and never overloaded.'],['Missing guard? Stop','Do not use powered equipment with a missing or defective guard; report it.'],['Faults','If an electrical hand tool gives off smoke, stop using it and report the defect.']]],
['Special site hazards',[['Confined spaces','They can contain hazardous atmospheres, flooding risks or lack oxygen - only enter with proper controls.'],['Underground cables','When exposing underground power cables, use safe hand excavation methods, not mechanical excavation.'],['Young workers','Young people may be at particular risk because of inexperience and lack of awareness.']]],
['Electrotechnical',[['Live work','Working live should only be considered by a responsible person after risk assessment; dead working is the normal safe approach.'],['UK supply','The UK nominal single-phase voltage is 230 V.'],['Electric shock','First remove the electrical danger safely, for example by switching off the supply, before helping a casualty.']]],
['Environmental',[['Waste liquids','If you are unsure how to dispose of oily waste liquid, ask your supervisor rather than guessing.'],['Dust','Control excessive dust: it can harm people and the wider environment.'],['Spills','Use bunds or drip trays to help prevent oil from reaching the environment.']]]
];
const questions=[
['What do the letters CDM stand for?',['Construction Design Management Regulations','Control of Demolition and Management Regulations','Construction Duty Management','Construction (Design and Management) Regulations'],3,'CDM means Construction (Design and Management) Regulations.'],
['If there is a risk of injury from lifting loads, what should you think about first?',['Whether the load needs to be lifted at all','Whether you can lift it quickly','Whether gloves are available','Whether it weighs over 25 kg'],0,'Avoiding the lift altogether is the first control to consider.'],
['What should be recorded following an accident?',['The date and time it occurred','The weather forecast','The worker’s next shift','The value of the tools involved'],0,'The date and time are required details for the accident record.'],
['Which item of PPE is most important when working on or near a highway?',['Safety footwear','Ear defenders','Safety helmet','High-visibility vest'],3,'High-visibility clothing helps ensure you can be seen around traffic.'],
['What is a likely result of long-term exposure to high noise levels?',['Hearing damage that can be corrected by surgery','Irreversible hearing damage','Better concentration','Temporary discomfort only'],1,'Noise-induced hearing damage is irreversible.'],
['What should you do if you hear the fire alarm?',['Continue if the work is urgent','Wait for instructions at your work area','Go to the designated place of safety','Phone the HSE inspector'],2,'Leave promptly and go to the designated place of safety.'],
['Who should inspect a ladder before it is used?',['The user','Only the foreman','The manufacturer','The client'],0,'The user must satisfy themselves it is in a safe condition before use.'],
['A powered hand tool has a missing blade guard. What should you do?',['Use it carefully','Remove it from use and report it','Borrow a guard from another tool','Wear extra PPE and carry on'],1,'Defective guards make equipment unsafe. Stop and report it.'],
['How should underground power cables be exposed?',['With a 360-degree excavator','With a mechanical breaker','By safe hand excavation','By flooding the trench'],2,'Mechanical excavation and power tools should not be used near buried cables.'],
['What is the nominal single-phase voltage in the UK?',['110 V','230 V','240 V','415 V'],1,'The nominal public single-phase supply is 230 volts.'],
['What can help prevent environmental harm from oil spillages?',['Flushing it with water','Leaving it to evaporate','A bund or drip tray','Covering it with soil'],2,'Containment such as bunds and drip trays prevents oil reaching the environment.']
];
const cards=[['CDM','Construction (Design and Management) Regulations'],['SWL','Safe Working Load'],['RIDDOR','Reporting of Injuries, Diseases and Dangerous Occurrences Regulations'],['PPE','Personal Protective Equipment'],['Risk assessment','A review of hazards and the practical controls needed'],['CO₂ extinguisher','Its nozzle becomes very cold in use'],['Live work','Only considered after risk assessment; dead working is normally safer'],['Weil’s disease','Leptospirosis, often linked to exposure to rat urine']];
let state=JSON.parse(localStorage.getItem('ecsReady')||'{"done":[],"streak":0,"answers":0,"correct":0}');let view='home',chosen=null,qi=0,qset=[],quizCorrect=0;const save=()=>{localStorage.setItem('ecsReady',JSON.stringify(state));document.querySelector('#streak').textContent=state.streak};
function nav(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function render(){if(view==='home')home();else if(view==='learn')learn();else if(view==='cards')cardsView();else if(view==='quiz')startQuiz(5);else if(view==='progress')progressView();else home()}
function go(v){view=v;chosen=null;render();window.scrollTo(0,0)}function html(s){document.querySelector('#app').innerHTML=s;nav();save()}
function home(){let d=state.done.length;html(`<h1>Make every revision session count.</h1><p class="sub">ECS Health, Safety & Environmental Awareness - one useful step at a time.</p><section class="hero"><span class="chip">TODAY'S FOCUS</span><h2>15-minute safety sprint</h2><p>Review a key topic, then check your knowledge with five questions.</p><button class="button" onclick="startQuiz(5)">Start today’s quiz</button></section><div class="section-head"><h2>Continue learning</h2><button class="linkbtn" onclick="go('learn')">See all</button></div><div class="card today"><div class="round">${d? '✓':'📘'}</div><div><h3>${d?`${d} topic${d===1?'':'s'} studied`:'Start with the essentials'}</h3><small>${d? 'Keep building your recall.':'Short lessons, then quiz yourself.'}</small></div></div><div class="section-head"><h2>Your progress</h2></div><div class="card"><div class="statgrid"><div class="stat"><strong>${d}/11</strong><small>Topics</small></div><div class="stat"><strong>${state.answers?Math.round(state.correct/state.answers*100):0}%</strong><small>Accuracy</small></div><div class="stat"><strong>${state.answers}</strong><small>Answered</small></div></div><div class="bar"><i style="width:${d/11*100}%"></i></div></div>`)}
function learn(){html(`<button class="back" onclick="go('home')">← Home</button><h1>Learn the guide</h1><p class="sub">Read the essentials, then mark a topic complete when it feels familiar.</p><div class="grid topics">${topics.map((t,i)=>`<button class="topic" onclick="topic(${i})"><span class="icon">${t[1]}</span><h3>${t[0]}</h3><small>${state.done.includes(i)?'✓ Complete':t[2]}</small><div class="bar"><i style="width:${state.done.includes(i)?100:0}%"></i></div></button>`).join('')}</div>`)}
function topic(i){let l=lessons[i];html(`<button class="back" onclick="go('learn')">← All topics</button><span class="chip">TOPIC ${i+1} OF 11</span><h1>${l[0]}</h1><p class="sub">Read these high-value reminders, drawn from the revision guide.</p>${l[1].map(x=>`<article class="lesson"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}<div class="actions"><button class="button" onclick="complete(${i})">${state.done.includes(i)?'Completed ✓':'Mark as learned'}</button><button class="button secondary" onclick="startQuiz(5)">Test me</button></div>`)}
function cardsView(){let c=cards[cardIndex%cards.length],flip=cardFlip;html(`<button class="back" onclick="go('home')">← Home</button><h1>Flashcards</h1><p class="sub">Say the answer aloud, then tap to reveal it.</p><article class="card flash" onclick="cardFlip=!cardFlip;cardsView()">${flip?`<div><span class="chip">ANSWER</span><div class="answer">${c[1]}</div></div>`:`<div><span class="chip">TERM</span><div class="term">${c[0]}</div></div>`}<small class="hint">Tap card to ${flip?'show term':'reveal answer'}</small></article><div class="controls"><button class="button ghost" onclick="cardIndex=(cardIndex+cards.length-1)%cards.length;cardFlip=false;cardsView()">← Previous</button><strong>${cardIndex%cards.length+1} / ${cards.length}</strong><button class="button" onclick="cardIndex=(cardIndex+1)%cards.length;cardFlip=false;cardsView()">Next →</button></div>`)}let cardIndex=0,cardFlip=false;
function progressView(){let accuracy=state.answers?Math.round(state.correct/state.answers*100):0;html(`<button class="back" onclick="go('home')">← Home</button><h1>Your progress</h1><p class="sub">Progress is private and stays in this browser.</p><div class="card"><div class="statgrid"><div class="stat"><strong>${state.done.length}/11</strong><small>Topics learned</small></div><div class="stat"><strong>${accuracy}%</strong><small>Quiz accuracy</small></div><div class="stat"><strong>${state.answers}</strong><small>Questions answered</small></div></div></div><div class="section-head"><h2>Topic checklist</h2></div><div class="grid">${topics.map((t,i)=>`<div class="card today"><div class="round">${state.done.includes(i)?'✓':t[1]}</div><div><h3>${t[0]}</h3><small>${state.done.includes(i)?'Complete':'Not yet completed'}</small></div></div>`).join('')}</div><div class="actions"><button class="button" onclick="startQuiz(questions.length)">Take full practice quiz</button><button class="button ghost" onclick="resetProgress()">Reset this device’s progress</button></div>`)}
function resetProgress(){if(!confirm('Reset all saved topic and quiz progress on this device?'))return;state={done:[],streak:0,answers:0,correct:0};save();go('home')}
function startQuiz(n=questions.length){qset=[...questions].sort(()=>Math.random()-.5).slice(0,n);qi=0;chosen=null;quizCorrect=0;view='quiz';quiz()}function quiz(){if(qi>=qset.length)return result();let q=qset[qi];html(`<button class="back" onclick="go('home')">← Exit quiz</button><div class="chip">QUESTION ${qi+1} OF ${qset.length}</div><div class="bar"><i style="width:${qi/qset.length*100}%"></i></div><article class="question"><h2>${q[0]}</h2>${q[1].map((x,i)=>`<button class="option ${chosen!==null?(i===q[2]?'good':i===chosen?'bad':''):''}" onclick="answer(${i})"><span class="letter">${'ABCD'[i]}</span><span>${x}</span></button>`).join('')}${chosen!==null?`<div class="explain"><b>${chosen===q[2]?'Correct!':'Not quite.'}</b> ${q[3]}</div><div class="actions"><button class="button" onclick="nextQ()">${qi===qset.length-1?'See results':'Next question'}</button></div>`:''}</article>`)}function answer(i){if(chosen!==null)return;chosen=i;state.answers++;if(i===qset[qi][2]){state.correct++;quizCorrect++}save();quiz()}function nextQ(){qi++;chosen=null;quiz()}function result(){let percent=Math.round(quizCorrect/qset.length*100);html(`<section class="card result"><div class="score">${quizCorrect}/${qset.length}</div><h1>${percent>=80?'Excellent work!':percent>=60?'Good progress.':'Keep practising.'}</h1><p class="sub">${percent}% on this quiz. Your answer history is saved on this device.</p><div class="actions" style="justify-content:center"><button class="button" onclick="startQuiz(5)">Try another set</button><button class="button secondary" onclick="go('learn')">Review topics</button></div></section>`)}function complete(i){if(!state.done.includes(i)){state.done.push(i);state.streak=Math.max(1,state.streak);save()}topic(i)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
Object.assign(window,{go,home,learn,topic,cardsView,progressView,startQuiz,answer,nextQ,complete,resetProgress});
window.addEventListener('error',()=>{document.querySelector('#app').innerHTML='<section class="card result"><h1>Something went wrong.</h1><p class="sub">Refresh the page once. If it continues, clear this site’s data and try again.</p></section>'});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
